// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.LoginUserAsync(BiteAlert.Modules.AuthModule.LoginUserRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.LoginUserResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.RegisterUserAsync(BiteAlert.Modules.AuthModule.RegisterUserRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.RegisterUserResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.UpdatePasswordAsync(System.String,BiteAlert.Modules.AuthModule.UpdatePasswordRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.UserProfileResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.UpdateProfileAsync(System.String,BiteAlert.Modules.AuthModule.UserProfileRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.UserProfileResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.ProductModule.ProductService.CreateAsync(System.String,BiteAlert.Modules.ProductModule.UpsertProductRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.ProductModule.UpsertProductResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.ProductModule.ProductService.GetProductByIdAsync(System.String)~System.Threading.Tasks.Task{BiteAlert.Modules.ProductModule.UpsertProductResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.StartupConfigs.Seeder.SeedRoles(System.IServiceProvider)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.V1.AuthController.RegisterUser(BiteAlert.Modules.AuthModule.RegisterUserRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.UpdatePasswordAsync(System.String,BiteAlert.Modules.AuthModule.UpdatePasswordRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.AuthResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.V1.AuthController.LoginUser(BiteAlert.Modules.AuthModule.LoginUserRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.ProductModule.V1.ProductsController.Create(BiteAlert.Modules.ProductModule.UpsertProductRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.ProductModule.V1.ProductsController.Update(System.String,BiteAlert.Modules.ProductModule.UpsertProductRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.UserModule.UserService.UpdateProfileAsync(System.String,BiteAlert.Modules.UserModule.UserProfileRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.UserModule.UserProfileResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.UserModule.V1.UsersController.UpdateProfile(BiteAlert.Modules.UserModule.UserProfileRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.VendorModule.V1.VendorsController.RegisterVendor(BiteAlert.Modules.VendorModule.UpsertVendorRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.VendorModule.V1.VendorsController.UpdateBusinessInfo(BiteAlert.Modules.VendorModule.UpsertVendorRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.LoginUserAsync(BiteAlert.Modules.AuthModule.LoginUserRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.AuthResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.RegisterUserAsync(BiteAlert.Modules.AuthModule.RegisterUserRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.AuthResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.AuthModule.AuthService.VerifyEmailAsync(System.String,System.String)~System.Threading.Tasks.Task{BiteAlert.Modules.AuthModule.AuthResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.UserModule.UserService.SelectRoleAsync(System.String,System.String)~System.Threading.Tasks.Task{BiteAlert.Modules.UserModule.UserProfileResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.VendorModule.VendorService.RegisterVendorAsync(System.String,BiteAlert.Modules.VendorModule.UpsertVendorRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.VendorModule.UpsertVendorResponse}")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:BiteAlert.Modules.VendorModule.VendorService.UpdateVendorBusinessInfo(System.String,BiteAlert.Modules.VendorModule.UpsertVendorRequest)~System.Threading.Tasks.Task{BiteAlert.Modules.VendorModule.UpsertVendorResponse}")]
